### PR TITLE
prepend msg. to fields in sql processor, changed styling for zoom in/out panel

### PR DESCRIPTION
**Pull request by shahsank3t**
1. Prepending "msg." to fields in SQL Processor for AthenaX
2. Changed Styling for Zoom controls
3. Changed text font size in all the forms

### CODE REVIEW

**Comment by shahsank3t** [comment]
4. Added missing icons

**Comment by shahsank3t** [comment]
5. grouping of engine type in add workflow form

**Comment by shahsank3t** [comment]
6. changed components styling as per the mocks

**Comment by shahsank3t** [comment]
7. Fixed icons in workflow editor looking squished

**Comment by harshach** [comment]
Merged in.

**Pull request closed without merging**
